# Generated by Django 6.0 on 2025-12-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_professionals", "0002_remove_healthprofessional_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthprofessional",
            name="address",
            field=models.TextField(default=1, verbose_name="Endereço"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="healthprofessional",
            name="contact",
            field=models.CharField(
                default="Endereço não informado", max_length=100, verbose_name="Contato"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="healthprofessional",
            name="profession",
            field=models.CharField(
                default="Endereço não informado",
                max_length=100,
                verbose_name="Profissão",
            ),
            preserve_default=False,
        ),
    ]
