# Generated by Django 6.0 on 2025-12-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_remove_appointments_professional_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointments",
            old_name="data",
            new_name="date",
        ),
    ]
