# Generated by Django 6.0 on 2025-12-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("health_professionals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthprofessional",
            name="address",
        ),
        migrations.RemoveField(
            model_name="healthprofessional",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="healthprofessional",
            name="profession",
        ),
    ]
