# Generated by Django 6.0 on 2025-12-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthProfessional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social_name",
                    models.CharField(max_length=200, verbose_name="Nome social"),
                ),
                (
                    "profession",
                    models.CharField(max_length=100, verbose_name="Profissão"),
                ),
                ("address", models.TextField(verbose_name="Endereço")),
                ("contact", models.CharField(max_length=100, verbose_name="Contato")),
            ],
        ),
    ]
