# Generated by Django 6.0 on 2025-12-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_professionals', '0003_healthprofessional_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthprofessional',
            options={'ordering': ['social_name'], 'verbose_name': 'Profissional de Saúde', 'verbose_name_plural': 'Profissionais de Saúde'},
        ),
        migrations.AddConstraint(
            model_name='healthprofessional',
            constraint=models.UniqueConstraint(fields=('social_name', 'profession'), name='unique_professional'),
        ),
    ]
