# Generated by Django 6.0 on 2025-12-20 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("health_professionals", "0003_healthprofessional_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointments",
            name="professional",
        ),
        migrations.AddField(
            model_name="appointments",
            name="health_professional",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="health_professionals.healthprofessional",
                verbose_name="Profissional",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointments",
            name="data",
            field=models.DateField(verbose_name="Data"),
        ),
    ]
