# Generated by Django 6.0 on 2025-12-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_data_appointments_date'),
        ('health_professionals', '0004_alter_healthprofessional_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ['date'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterUniqueTogether(
            name='appointments',
            unique_together={('date', 'health_professional')},
        ),
    ]
